import shuffle from 'shuffle-array';

import { CardData } from '../types';

const cards: CardData[] = [
  { id: 1,  color: 'blue', value: '0' },
  { id: 2,  color: 'blue', value: '1' },
  { id: 3,  color: 'blue', value: '1' },
  { id: 4,  color: 'blue', value: '2' },
  { id: 5,  color: 'blue', value: '2' },
  { id: 6,  color: 'blue', value: '3' },
  { id: 7,  color: 'blue', value: '3' },
  { id: 8,  color: 'blue', value: '4' },
  { id: 9,  color: 'blue', value: '4' },
  { id: 10, color: 'blue', value: '5' },
  { id: 11, color: 'blue', value: '5' },
  { id: 12, color: 'blue', value: '6' },
  { id: 13, color: 'blue', value: '6' },
  { id: 14, color: 'blue', value: '7' },
  { id: 15, color: 'blue', value: '7' },
  { id: 16, color: 'blue', value: '8' },
  { id: 17, color: 'blue', value: '8' },
  { id: 18, color: 'blue', value: '9' },
  { id: 19, color: 'blue', value: '9' },
  { id: 20, color: 'blue', value: 'reverse' },
  { id: 21, color: 'blue', value: 'skip' },
  { id: 22, color: 'green', value: '0' },
  { id: 23, color: 'green', value: '1' },
  { id: 24, color: 'green', value: '1' },
  { id: 25, color: 'green', value: '2' },
  { id: 26, color: 'green', value: '2' },
  { id: 27, color: 'green', value: '3' },
  { id: 28, color: 'green', value: '3' },
  { id: 29, color: 'green', value: '4' },
  { id: 30, color: 'green', value: '4' },
  { id: 31, color: 'green', value: '5' },
  { id: 32, color: 'green', value: '5' },
  { id: 33, color: 'green', value: '6' },
  { id: 34, color: 'green', value: '6' },
  { id: 35, color: 'green', value: '7' },
  { id: 36, color: 'green', value: '7' },
  { id: 37, color: 'green', value: '8' },
  { id: 38, color: 'green', value: '8' },
  { id: 39, color: 'green', value: '9' },
  { id: 40, color: 'green', value: '9' },
  { id: 41, color: 'green', value: 'reverse' },
  { id: 42, color: 'green', value: 'skip' },
  { id: 43, color: 'red', value: '0' },
  { id: 44, color: 'red', value: '1' },
  { id: 45, color: 'red', value: '1' },
  { id: 46, color: 'red', value: '2' },
  { id: 47, color: 'red', value: '2' },
  { id: 48, color: 'red', value: '3' },
  { id: 49, color: 'red', value: '3' },
  { id: 50, color: 'red', value: '4' },
  { id: 51, color: 'red', value: '4' },
  { id: 52, color: 'red', value: '5' },
  { id: 53, color: 'red', value: '5' },
  { id: 54, color: 'red', value: '6' },
  { id: 55, color: 'red', value: '6' },
  { id: 56, color: 'red', value: '7' },
  { id: 57, color: 'red', value: '7' },
  { id: 58, color: 'red', value: '8' },
  { id: 59, color: 'red', value: '8' },
  { id: 60, color: 'red', value: '9' },
  { id: 61, color: 'red', value: '9' },
  { id: 62, color: 'red', value: 'reverse' },
  { id: 63, color: 'red', value: 'skip' },
  { id: 64, color: 'yellow', value: '0' },
  { id: 65, color: 'yellow', value: '1' },
  { id: 66, color: 'yellow', value: '1' },
  { id: 67, color: 'yellow', value: '2' },
  { id: 68, color: 'yellow', value: '2' },
  { id: 69, color: 'yellow', value: '3' },
  { id: 70, color: 'yellow', value: '3' },
  { id: 71, color: 'yellow', value: '4' },
  { id: 72, color: 'yellow', value: '4' },
  { id: 73, color: 'yellow', value: '5' },
  { id: 74, color: 'yellow', value: '5' },
  { id: 75, color: 'yellow', value: '6' },
  { id: 76, color: 'yellow', value: '6' },
  { id: 77, color: 'yellow', value: '7' },
  { id: 78, color: 'yellow', value: '7' },
  { id: 79, color: 'yellow', value: '8' },
  { id: 80, color: 'yellow', value: '8' },
  { id: 81, color: 'yellow', value: '9' },
  { id: 82, color: 'yellow', value: '9' },
  { id: 83, color: 'yellow', value: 'reverse' },
  { id: 84, color: 'yellow', value: 'skip' }
];

const initialState = shuffle(cards, { copy: true });

export default initialState;